site_name: AIOPSLAB

theme: 
  name: material
  logo: imgs/logo.png
  palette:
    primary: blue

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://fosstodon.org/@squidfunk

extra_css:
  - assets/css/style.css
  - assets/css/all.min.css

extra_javascript:
  - assets/js/leaderboard.js

copyright: Copyright &copy; 2024 AIOPSLAB

